@echo off
echo Activation de l'environnement virtuel...
call mon_env\Scripts\activate.bat
echo Lancement de l'interface graphique...
python main.py --gui
echo.
echo Appuyez sur une touche pour fermer...
pause > nul